DROP TABLE IF EXISTS BOOK;

DROP TABLE IF EXISTS AUTHOR;

DROP TABLE IF EXISTS GENRE;

CREATE TABLE GENRE
(
    ID IDENTITY PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX GENRE_UNIQUE ON GENRE (NAME);

CREATE TABLE AUTHOR
(
    ID IDENTITY PRIMARY KEY,
    NAME    VARCHAR(255),
    SURNAME VARCHAR(255)
);

CREATE UNIQUE INDEX AUTHOR_UNIQUE ON AUTHOR (NAME, SURNAME);

CREATE TABLE BOOK
(
    ID IDENTITY PRIMARY KEY,
    TITLE      VARCHAR(255),
    GENRE_ID  BIGINT REFERENCES GENRE (ID),
    AUTHOR_ID BIGINT REFERENCES AUTHOR (ID)
);
